
const lessonData = {
    "01_TheAshCloud.mp3": [{
        text: `Maria was a scientist studying a volcano. She thought it was safe, but the volcano exploded suddenly. A huge cloud of hot ash and rock came down the mountain. Maria jumped into her truck and drove fast. The ash cloud turned the day into night. She could not see the road. The engine stopped because of the dust. She had to get out and run. The air was hot and poisonous. She put a wet cloth over her mouth to breathe. She ran until she found a small cave to hide in. She waited there until the ash settled. A rescue team found her covered in gray dust.`,
        dict: { "was": "idi", "scientist": "bilim insanı", "studying": "inceleyen", "volcano": "yanardağ", "thought": "düşündü", "safe": "güvenli", "exploded": "patladı", "suddenly": "aniden", "huge": "kocaman", "cloud": "bulut", "hot": "sıcak", "ash": "kül", "rock": "kaya", "came down": "aşağı geldi", "mountain": "dağ", "jumped": "atladı", "truck": "kamyonet", "drove": "sürdü", "fast": "hızlı", "turned": "dönüştürdü", "day": "gündüz", "night": "gece", "could not": "yapamadı", "see": "görmek", "road": "yol", "engine": "motor", "stopped": "durdu", "because of": "yüzünden", "dust": "toz", "had to": "zorundaydı", "get out": "dışarı çıkmak", "run": "koşmak", "air": "hava", "poisonous": "zehirli", "put": "koydu", "wet": "ıslak", "cloth": "bez", "over": "üzerine", "mouth": "ağız", "breathe": "nefes almak", "ran": "koştu", "until": "kadar", "found": "buldu", "small": "küçük", "cave": "mağara", "hide in": "içinde saklanmak", "waited": "bekledi", "there": "orada", "settled": "yatıştı/çöktü", "rescue": "kurtarma", "team": "ekip", "covered": "kaplı", "gray": "gri" },
        questions: [ {q:"Was Maria a scientist?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the volcano explode suddenly?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she drive a car?", a_en:"No", a_tr:"Hayır"}, {q:"Was the air poisonous?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she use a wet cloth?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she hide in a tree?", a_en:"No", a_tr:"Hayır"}, {q:"Did a rescue team find her?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "02_TheBigWave.mp3": [{
        text: `Sari was playing on a beach in Thailand. She saw the ocean water pull back very far. It looked strange. Then, a massive wall of water came back. It was a tsunami. The water hit the land with great power. Sari grabbed a palm tree and climbed up. The water destroyed houses and carried cars away below her. She held onto the tree for hours. Debris and wood hit her legs, but she did not let go. She was scared she would fall into the fast water. When the water finally went down, she was safe but alone. Her family found her later at a safe zone on a hill.`,
        dict: { "playing": "oynayan", "beach": "plaj", "saw": "gördü", "ocean": "okyanus", "water": "su", "pull back": "geri çekilmek", "very": "çok", "far": "uzak", "looked": "göründü", "strange": "garip", "Then": "sonra", "massive": "muazzam", "wall": "duvar", "came back": "geri geldi", "hit": "çarptı", "land": "kara", "with": "ile", "great": "büyük/harika", "power": "güç", "grabbed": "yakaladı", "palm tree": "palmiye ağacı", "climbed up": "yukarı tırmandı", "destroyed": "yok etti", "houses": "evler", "carried away": "alıp götürdü", "cars": "arabalar", "below": "altında", "held onto": "tutundu", "hours": "saatler", "Debris": "enkaz", "wood": "ahşap", "legs": "bacaklar", "did not": "yapmadı", "let go": "bırakmak", "scared": "korkmuş", "would fall": "düşecekti", "fast": "hızlı", "When": "zaman/olduğunda", "finally": "sonunda", "went down": "aşağı indi", "safe": "güvenli", "alone": "yalnız", "family": "aile", "found": "buldu", "later": "daha sonra", "zone": "bölge", "hill": "tepe" },
        questions: [ {q:"Was Sari in Thailand?", a_en:"Yes", a_tr:"Evet"}, {q:"Did a massive wall of water come?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she grab a palm tree?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she let go of the tree?", a_en:"No", a_tr:"Hayır"}, {q:"Did debris hit her legs?", a_en:"Yes", a_tr:"Evet"}, {q:"Was she alone when the water went down?", a_en:"Yes", a_tr:"Evet"}, {q:"Did her family find her later?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "03_TheDeepDark.mp3": [{
        text: `Luis was the boss of a copper mine. He worked with 32 other men deep underground. One day, the mine collapsed. A lot of rock blocked the exit. The men were trapped in a small safety room. It was hot, dark, and dusty. They only had food for two days. Luis became a strong leader. He told the men to eat only one spoon of tuna every two days to make the food last. They waited in the dark for 17 days. They did not know if help was coming. Finally, a drill broke through the ceiling. The men sent a note up that said, "We are all okay." Rescuers drilled a bigger hole and saved them.`,
        dict: { "boss": "patron", "copper": "bakır", "mine": "maden", "worked": "çalıştı", "other": "diğer", "men": "adamlar", "deep": "derin", "underground": "yeraltı", "collapsed": "çöktü", "rock": "kaya", "blocked": "kapattı/engelledi", "exit": "çıkış", "trapped": "kapana kısılmış", "small": "küçük", "safety": "güvenlik", "room": "oda", "hot": "sıcak", "dark": "karanlık", "dusty": "tozlu", "only": "sadece", "had": "sahipti", "food": "yiyecek", "days": "günler", "became": "oldu", "strong": "güçlü", "leader": "lider", "told": "söyledi", "eat": "yemek", "one": "bir", "spoon": "kaşık", "tuna": "ton balığı", "every": "her", "make": "yapmak", "last": "dayanmak/yetmek", "waited": "beklediler", "did not know": "bilmiyorlardı", "help": "yardım", "coming": "geliyor", "Finally": "sonunda", "drill": "matkap", "broke through": "delip geçti", "ceiling": "tavan", "sent": "gönderdi", "note": "not", "said": "dedi", "okay": "iyi/tamam", "Rescuers": "kurtarıcılar", "drilled": "deldi", "bigger": "daha büyük", "hole": "delik", "saved": "kurtardı" },
        questions: [ {q:"Was Luis the boss?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the mine collapse?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they have food for many days?", a_en:"No", a_tr:"Hayır"}, {q:"Did they eat tuna?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they wait for 17 days?", a_en:"Yes", a_tr:"Evet"}, {q:"Did a drill break the ceiling?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they send a note?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "04_TheDrift.mp3": [{
        text: `Arthur loved the ocean. He was sailing around the world alone on his boat. One night, something large hit his boat in the middle of the Atlantic Ocean. The boat sank very fast. Arthur jumped into a small rubber raft. He only had a speargun and a little bit of water. He floated on the ocean for 76 days. The sun was very hot, and he was always thirsty. He had a machine to make fresh water from salt water, but it broke often. He had to fix it with old parts to survive. Big fish hit the bottom of his raft, and sharks swam nearby. He saw big ships, but they did not see him. Finally, fishermen saw birds flying around his raft and found him.`,
        dict: { "loved": "sevdi", "ocean": "okyanus", "sailing": "yelken açan/denize açılan", "around": "etrafında", "world": "dünya", "alone": "yalnız", "boat": "tekne", "night": "gece", "large": "büyük", "hit": "çarptı", "middle": "orta", "sank": "battı", "very": "çok", "fast": "hızlı", "jumped": "atladı", "small": "küçük", "rubber": "kauçuk", "raft": "sal", "only": "sadece", "had": "sahipti", "speargun": "zıpkın", "little": "az/küçük", "bit": "biraz", "water": "su", "floated": "süzüldü/yüzdü", "days": "günler", "sun": "güneş", "hot": "sıcak", "always": "her zaman", "thirsty": "susamış", "machine": "makine", "make": "yapmak", "fresh": "taze", "salt": "tuz", "broke": "bozuldu", "often": "sık sık", "fix": "tamir etmek", "old": "eski", "parts": "parçalar", "survive": "hayatta kalmak", "Big": "büyük", "fish": "balık", "bottom": "alt/dip", "sharks": "köpekbalıkları", "swam": "yüzdü", "nearby": "yakında", "saw": "gördü", "ships": "gemiler", "did not": "yapmadı", "see": "görmek", "Finally": "sonunda", "fishermen": "balıkçılar", "birds": "kuşlar", "flying": "uçan", "found": "buldu" },
        questions: [ {q:"Was Arthur sailing alone?", a_en:"Yes", a_tr:"Evet"}, {q:"Did his boat sink fast?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he have a lot of water?", a_en:"No", a_tr:"Hayır"}, {q:"Did he float for 76 days?", a_en:"Yes", a_tr:"Evet"}, {q:"Did sharks swim nearby?", a_en:"Yes", a_tr:"Evet"}, {q:"Did big ships see him?", a_en:"No", a_tr:"Hayır"}, {q:"Did fishermen find him?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "05_TheFallenCity.mp3": [{
        text: `Elena was working in her office in a tall building. Suddenly, the ground shook violently. It was a massive earthquake. The building collapsed. Elena woke up in the dark. She was trapped under heavy concrete and metal. She could not move her legs. The air was full of dust, and it was hard to breathe. She had no water. She heard other people crying, but then they stopped. She found a metal pipe near her head. She used a rock to hit the pipe three times every hour. She did this for two days. Firefighters heard the noise and dug through the rocks to pull her out.`,
        dict: { "working": "çalışan", "office": "ofis", "tall": "uzun", "building": "bina", "Suddenly": "aniden", "ground": "yer/zemin", "shook": "sallandı", "violently": "şiddetle", "massive": "muazzam", "earthquake": "deprem", "collapsed": "çöktü", "woke up": "uyandı", "dark": "karanlık", "trapped": "kapana kısılmış", "under": "altında", "heavy": "ağır", "concrete": "beton", "metal": "metal", "could not": "yapamadı", "move": "hareket ettirmek", "legs": "bacaklar", "air": "hava", "full": "dolu", "dust": "toz", "hard": "zor", "breathe": "nefes almak", "had": "sahipti", "no": "yok/hiç", "water": "su", "heard": "duydu", "other": "diğer", "people": "insanlar", "crying": "ağlayan", "stopped": "durdular", "found": "buldu", "pipe": "boru", "near": "yakın", "head": "kafa", "used": "kullandı", "rock": "kaya", "hit": "vurmak", "three": "üç", "times": "kez/defa", "every": "her", "hour": "saat", "did": "yaptı", "days": "günler", "Firefighters": "itfaiyeciler", "noise": "ses/gürültü", "dug": "kazdı", "through": "içinden", "rocks": "kayalar", "pull": "çekmek", "out": "dışarı" },
        questions: [ {q:"Was Elena in a tall building?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the building collapse?", a_en:"Yes", a_tr:"Evet"}, {q:"Was she trapped in the dark?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she have water?", a_en:"No", a_tr:"Hayır"}, {q:"Did she use a rock to hit a pipe?", a_en:"Yes", a_tr:"Evet"}, {q:"Did firefighters hear her?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they pull her out?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "06_TheFrozenIsland.mp3": [{
        text: `Captain James led a team to cross Antarctica. Their ship got stuck in thick ice and sank. The 28 men camped on the floating ice for months. When the ice melted, they used small lifeboats to go to a rocky island. It was cold and empty. James knew nobody would find them there. He took five men and one small boat. They sailed 800 miles across the most dangerous ocean in the world. They fought huge waves and strong winds for weeks. They reached a station on South Georgia Island. James returned with a rescue ship to save the rest of his crew. All the men survived.`,
        dict: { "led": "yönetti/önderlik etti", "team": "ekip", "cross": "geçmek", "ship": "gemi", "got stuck": "sıkıştı", "thick": "kalın", "ice": "buz", "sank": "battı", "men": "adamlar", "camped": "kamp yaptı", "floating": "yüzen", "months": "aylar", "melted": "eridi", "used": "kullandı", "small": "küçük", "lifeboats": "cankurtaran botları", "go": "gitmek", "rocky": "kayalık", "island": "ada", "cold": "soğuk", "empty": "boş", "knew": "biliyordu", "nobody": "hiç kimse", "find": "bulmak", "took": "aldı", "boat": "tekne", "sailed": "denize açıldı", "miles": "miller", "across": "karşısına", "most": "en", "dangerous": "tehlikeli", "ocean": "okyanus", "world": "dünya", "fought": "savaştı", "huge": "kocaman", "waves": "dalgalar", "strong": "güçlü", "winds": "rüzgarlar", "weeks": "haftalar", "reached": "ulaştı", "station": "istasyon", "returned": "geri döndü", "rescue": "kurtarma", "save": "kurtarmak", "rest": "geri kalan", "crew": "mürettebat", "survived": "hayatta kaldı" },
        questions: [ {q:"Did Captain James go to Antarctica?", a_en:"Yes", a_tr:"Evet"}, {q:"Did their ship sink?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they camp on ice?", a_en:"Yes", a_tr:"Evet"}, {q:"Did James take a small boat?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they fight huge waves?", a_en:"Yes", a_tr:"Evet"}, {q:"Did James return with a rescue ship?", a_en:"Yes", a_tr:"Evet"}, {q:"Did all the men survive?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "07_TheGreatBear.mp3": [{
        text: `Hugh was a hunter in the deep forest. He surprised a mother bear and her cubs. The bear attacked him. It bit his leg and broke his ribs. Hugh pretended to be dead. The bear left him. Hugh was badly hurt and could not walk. He was miles from his camp. His friends were too far ahead to hear him. He had to crawl on the ground. He was in great pain. He ate berries and drank water from puddles. He crawled for five days. He had to hide from wolves. Finally, he reached a river and floated down on a log until his friends found him.`,
        dict: { "hunter": "avcı", "deep": "derin", "forest": "orman", "surprised": "şaşırttı", "mother": "anne", "bear": "ayı", "cubs": "yavrular", "attacked": "saldırdı", "bit": "ısırdı", "leg": "bacak", "broke": "kırdı", "ribs": "kaburgalar", "pretended": "numara yaptı", "dead": "ölü", "left": "bıraktı", "badly": "kötü bir şekilde", "hurt": "yaralı", "could not": "yapamadı", "walk": "yürümek", "miles": "miller", "camp": "kamp", "friends": "arkadaşlar", "far": "uzak", "ahead": "ileride", "hear": "duymak", "had to": "zorundaydı", "crawl": "emeklemek", "ground": "yer/zemin", "great": "büyük", "pain": "acı", "ate": "yedi", "berries": "böğürtlenler", "drank": "içti", "water": "su", "puddles": "su birikintileri", "crawled": "emekledi", "days": "günler", "hide": "saklanmak", "wolves": "kurtlar", "Finally": "sonunda", "reached": "ulaştı", "river": "nehir", "floated": "süzüldü/yüzdü", "down": "aşağı", "log": "kütük", "until": "kadar", "found": "buldu" },
        questions: [ {q:"Was Hugh a hunter?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he surprise a mother bear?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he pretend to be dead?", a_en:"Yes", a_tr:"Evet"}, {q:"Could he walk?", a_en:"No", a_tr:"Hayır"}, {q:"Did he crawl for five days?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he hide from wolves?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he float down a river?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "08_TheHighWater.mp3": [{
        text: `Ken lived in a city near a big river. It rained for a week. The dam broke, and water rushed into the city. The water rose very fast, filling the first floor of his house. Ken climbed to the second floor, but the water kept rising. He had to climb out the window onto the roof. It was raining hard and very cold. He had no food. He watched cars floating by. He was afraid the house would wash away. He waved a red shirt at helicopters, but they were busy. He spent two nights on the roof. Finally, a neighbor with a boat came and took him to dry land.`,
        dict: { "lived": "yaşadı", "city": "şehir", "near": "yakın", "big": "büyük", "river": "nehir", "rained": "yağmur yağdı", "week": "hafta", "dam": "baraj", "broke": "kırıldı", "water": "su", "rushed": "hücum etti", "rose": "yükseldi", "very": "çok", "fast": "hızlı", "filling": "doldurarak", "first": "ilk", "floor": "kat", "house": "ev", "climbed": "tırmandı", "second": "ikinci", "kept": "devam etti", "rising": "yükselmeye", "had to": "zorundaydı", "out": "dışarı", "window": "pencere", "roof": "çatı", "hard": "şiddetli", "cold": "soğuk", "had": "sahipti", "no": "yok/hiç", "food": "yiyecek", "watched": "izledi", "cars": "arabalar", "floating": "yüzen", "afraid": "korkmuş", "wash away": "sürüklemek", "waved": "salladı", "red": "kırmızı", "shirt": "gömlek", "helicopters": "helikopterler", "busy": "meşgul", "spent": "geçirdi", "nights": "geceler", "Finally": "sonunda", "neighbor": "komşu", "boat": "tekne", "came": "geldi", "took": "aldı", "dry": "kuru", "land": "kara" },
        questions: [ {q:"Did the dam break?", a_en:"Yes", a_tr:"Evet"}, {q:"Did water fill the first floor?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he climb onto the roof?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he have food?", a_en:"No", a_tr:"Hayır"}, {q:"Did he wave a red shirt?", a_en:"Yes", a_tr:"Evet"}, {q:"Did helicopters rescue him?", a_en:"No", a_tr:"Hayır"}, {q:"Did he spend two nights on the roof?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "09_TheIcePocket.mp3": [{
        text: `Thomas was a cook on a big boat. Early in the morning, a big wave hit the boat. It turned over and sank to the bottom of the ocean. Thomas was in the bathroom. He was thrown around in the dark water. Luckily, he found an air pocket in a cabin. This was a small space with air, but he was trapped underwater. He sat there for 60 hours. It was freezing cold and pitch black. He could hear fish eating nearby. He tried to stay calm to save oxygen. He did not know if anyone was coming. Divers came to find dead bodies, but Thomas grabbed a diver's hand. The diver was shocked. They helped Thomas swim to the surface safely.`,
        dict: { "cook": "aşçı", "big": "büyük", "boat": "tekne", "Early": "erken", "morning": "sabah", "wave": "dalga", "hit": "çarptı", "turned over": "ters döndü", "sank": "battı", "bottom": "dip", "ocean": "okyanus", "bathroom": "banyo", "thrown": "fırlatılmış", "around": "etrafında", "dark": "karanlık", "water": "su", "Luckily": "şans eseri", "found": "buldu", "air pocket": "hava boşluğu", "cabin": "kabin", "small": "küçük", "space": "alan", "air": "hava", "trapped": "kapana kısılmış", "underwater": "sualtı", "sat": "oturdu", "there": "orada", "hours": "saatler", "freezing": "dondurucu", "cold": "soğuk", "pitch black": "zifiri karanlık", "could": "yapabilirdi", "hear": "duymak", "fish": "balık", "eating": "yiyen", "nearby": "yakınlarda", "tried": "denedi", "stay": "kalmak", "calm": "sakin", "save": "kurtarmak/tasarruf etmek", "oxygen": "oksijen", "did not know": "bilmiyordu", "anyone": "kimse", "coming": "geliyor", "Divers": "dalgıçlar", "came": "geldi", "find": "bulmak", "dead": "ölü", "bodies": "bedenler", "grabbed": "yakaladı", "diver's": "dalgıcın", "hand": "el", "shocked": "şok olmuş", "helped": "yardım etti", "swim": "yüzmek", "surface": "yüzey", "safely": "güvenle" },
        questions: [ {q:"Was Thomas a cook?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the boat sink?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he find an air pocket?", a_en:"Yes", a_tr:"Evet"}, {q:"Was it freezing cold?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he stay calm to save oxygen?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he grab a diver's hand?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the diver help him?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "10_TheLastOneLeft.mp3": [{
        text: `Elara joined an expedition to the Arctic to earn money. She was the only woman with four men. They went to a lonely island, but their supply ship never came. They ran out of food. Three men left to walk across the frozen sea for help, but they never returned. The last man got sick and died, leaving Elara all alone. She was scared, but she had to survive. She learned how to use a gun to hunt seals for food. She also had to scare away dangerous polar bears that came near her tent. She lived alone for two years. Finally, a ship arrived and found her alive and healthy.`,
        dict: { "joined": "katıldı", "expedition": "keşif", "Arctic": "Kuzey Kutbu", "earn": "kazanmak", "money": "para", "only": "sadece/tek", "woman": "kadın", "men": "adamlar", "went": "gitti", "lonely": "yalnız", "island": "ada", "supply": "erzak/ikmal", "ship": "gemi", "never": "asla", "came": "geldi", "ran out": "tükendi/bitti", "food": "yiyecek", "Three": "üç", "left": "ayrıldı", "walk": "yürümek", "across": "karşısına", "frozen": "donmuş", "sea": "deniz", "help": "yardım", "returned": "geri döndü", "last": "son", "man": "adam", "got sick": "hasta oldu", "died": "öldü", "leaving": "bırakarak", "all alone": "yapayalnız", "scared": "korkmuş", "had to": "zorundaydı", "survive": "hayatta kalmak", "learned": "öğrendi", "use": "kullanmak", "gun": "silah", "hunt": "avlamak", "seals": "foklar", "also": "ayrıca", "scare away": "korkutup kaçırmak", "dangerous": "tehlikeli", "polar bears": "kutup ayıları", "near": "yakın", "tent": "çadır", "lived": "yaşadı", "alone": "yalnız", "years": "yıllar", "Finally": "sonunda", "arrived": "vardı", "found": "buldu", "alive": "canlı", "healthy": "sağlıklı" },
        questions: [ {q:"Was Elara in the Arctic?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the supply ship come?", a_en:"No", a_tr:"Hayır"}, {q:"Did the last man die?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she hunt seals for food?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she scare away polar bears?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she live alone for two years?", a_en:"Yes", a_tr:"Evet"}, {q:"Was she alive and healthy?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "11_TheLonelyIsland.mp3": [{
        text: `Tom was a fisherman working alone near the Pacific islands. A terrible storm destroyed his boat. He grabbed a piece of wood and floated to a tiny, empty island. He was completely alone. He had no food and no tools. His challenge was to find fresh water. He learned to break coconuts to drink the milk. He also had to make a fire without matches to stay warm at night. He felt very lonely and talked to a volleyball he found on the beach to stay sane. He lived there for four years. One day, a plane saw the smoke from his fire and sent a boat to rescue him.`,
        dict: { "fisherman": "balıkçı", "working": "çalışan", "alone": "yalnız", "near": "yakın", "islands": "adalar", "terrible": "korkunç", "storm": "fırtına", "destroyed": "yok etti", "boat": "tekne", "grabbed": "yakaladı", "piece": "parça", "wood": "ahşap", "floated": "süzüldü/yüzdü", "tiny": "minik", "empty": "boş", "island": "ada", "completely": "tamamen", "had": "sahipti", "no": "hiç", "food": "yiyecek", "tools": "aletler", "challenge": "zorluk/meydan okuma", "find": "bulmak", "fresh": "taze", "water": "su", "learned": "öğrendi", "break": "kırmak", "coconuts": "hindistan cevizleri", "drink": "içmek", "milk": "süt", "also": "ayrıca", "had to": "zorundaydı", "make": "yapmak", "fire": "ateş", "without": "olmaksızın", "matches": "kibritler", "stay": "kalmak", "warm": "sıcak", "night": "gece", "felt": "hissetti", "lonely": "yalnız", "talked": "konuştu", "volleyball": "voleybol topu", "found": "buldu", "beach": "plaj", "sane": "aklı başında", "lived": "yaşadı", "there": "orada", "years": "yıllar", "One day": "bir gün", "plane": "uçak", "saw": "gördü", "smoke": "duman", "sent": "gönderdi", "rescue": "kurtarmak" },
        questions: [ {q:"Was Tom a fisherman?", a_en:"Yes", a_tr:"Evet"}, {q:"Did a storm destroy his boat?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he float to a tiny island?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he have tools?", a_en:"No", a_tr:"Hayır"}, {q:"Did he make a fire without matches?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he talk to a volleyball?", a_en:"Yes", a_tr:"Evet"}, {q:"Did a plane see his smoke?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "12_TheRedDirt.mp3": [{
        text: `The Smith family was driving across the Australian Outback. It was a very empty and hot place. Their car engine broke down. They were hundreds of miles from the nearest town. There was no phone signal. The father knew they should not leave the car because the car is easier to see from the sky. They had only two bottles of water. The heat was dangerous, over 40 degrees. They sat under the car for shade. They waited for four days. They were very weak. Finally, a plane flying overhead saw the sun reflecting off their car mirror and sent help.`,
        dict: { "family": "aile", "driving": "araba süren", "across": "karşısına/boyunca", "Outback": "taşra (Avustralya)", "empty": "boş", "hot": "sıcak", "place": "yer", "car": "araba", "engine": "motor", "broke down": "bozuldu", "hundreds": "yüzlerce", "miles": "miller", "nearest": "en yakın", "town": "kasaba", "no": "yok/hiç", "phone": "telefon", "signal": "sinyal", "father": "baba", "knew": "biliyordu", "should not": "yapmamalı", "leave": "ayrılmak/bırakmak", "because": "çünkü", "easier": "daha kolay", "see": "görmek", "sky": "gökyüzü", "had": "sahipti", "only": "sadece", "two": "iki", "bottles": "şişeler", "water": "su", "heat": "ısı/sıcaklık", "dangerous": "tehlikeli", "over": "üzerinde", "degrees": "derece", "sat": "oturdular", "under": "altında", "shade": "gölge", "waited": "beklediler", "days": "günler", "very": "çok", "weak": "zayıf", "Finally": "sonunda", "plane": "uçak", "flying": "uçan", "overhead": "tepede", "saw": "gördü", "sun": "güneş", "reflecting": "yansıyan", "mirror": "ayna", "sent": "gönderdi", "help": "yardım" },
        questions: [ {q:"Was the family in the Australian Outback?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the car engine break down?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they have phone signal?", a_en:"No", a_tr:"Hayır"}, {q:"Did they sit under the car?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they wait for four days?", a_en:"Yes", a_tr:"Evet"}, {q:"Were they very weak?", a_en:"Yes", a_tr:"Evet"}, {q:"Did a plane see the mirror?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "13_TheRisingWater.mp3": [{
        text: `A soccer coach and 12 young boys went to explore a cave. It was a fun trip, but then it started to rain very hard outside. Water rushed into the cave. The group ran deeper inside to find dry ground. They were trapped on a small rock shelf. The water blocked the exit. They had no food and only flashlights. The air was getting thin. The coach taught the boys how to meditate to stay calm and save energy. They sat there for nine days in the dark. British divers found them. It took many days to teach the boys how to dive underwater to get out.`,
        dict: { "soccer": "futbol", "coach": "koç", "young": "genç", "boys": "çocuklar", "went": "gitti", "explore": "keşfetmek", "cave": "mağara", "fun": "eğlenceli", "trip": "gezi", "then": "sonra", "started": "başladı", "rain": "yağmur yağmak", "very": "çok", "hard": "şiddetli", "outside": "dışarıda", "Water": "su", "rushed": "hücum etti", "group": "grup", "ran": "koştu", "deeper": "daha derin", "inside": "içeri", "find": "bulmak", "dry": "kuru", "ground": "yer/zemin", "trapped": "kapana kısılmış", "small": "küçük", "rock": "kaya", "shelf": "raf/çıkıntı", "blocked": "kapattı", "exit": "çıkış", "had": "sahipti", "no": "yok", "food": "yiyecek", "only": "sadece", "flashlights": "el fenerleri", "air": "hava", "getting": "oluyordu", "thin": "ince/az", "taught": "öğretti", "meditate": "meditasyon yapmak", "stay": "kalmak", "calm": "sakin", "save": "korumak", "energy": "enerji", "sat": "oturdular", "there": "orada", "nine": "dokuz", "days": "günler", "dark": "karanlık", "British": "İngiliz", "divers": "dalgıçlar", "found": "buldu", "took": "aldı/sürdü", "many": "birçok", "teach": "öğretmek", "dive": "dalmak", "underwater": "sualtı", "get out": "çıkmak" },
        questions: [ {q:"Did they explore a cave?", a_en:"Yes", a_tr:"Evet"}, {q:"Did water rush into the cave?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they have food?", a_en:"No", a_tr:"Hayır"}, {q:"Did the coach teach them to meditate?", a_en:"Yes", a_tr:"Evet"}, {q:"Were they in the dark for nine days?", a_en:"Yes", a_tr:"Evet"}, {q:"Did British divers find them?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the boys learn to dive?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "14_TheRiversPath.mp3": [{
        text: `Maya was a 17-year-old student. She flew with her mother over the Amazon jungle. Suddenly, lightning hit the plane. It broke apart in the sky. Maya fell into the trees, which saved her life. She woke up alone and hurt. Everyone else was dead. She remembered her father’s advice: "If you are lost, follow the river to find people." She walked for 11 days in the deep jungle. She had cuts on her arms, and insects laid eggs in her wounds. It was very painful. She saw crocodiles in the water but kept walking. She was very hungry and tired. Finally, she found a small boat and waited. Workers found her the next day and took her to a hospital.`,
        dict: { "student": "öğrenci", "flew": "uçtu", "mother": "anne", "over": "üzerinde", "jungle": "orman", "Suddenly": "aniden", "lightning": "şimşek", "hit": "çarptı", "plane": "uçak", "broke apart": "parçalara ayrıldı", "sky": "gökyüzü", "fell": "düştü", "trees": "ağaçlar", "saved": "kurtardı", "life": "hayat", "woke up": "uyandı", "alone": "yalnız", "hurt": "yaralı", "Everyone": "herkes", "else": "başka", "dead": "ölü", "remembered": "hatırladı", "father's": "babanın", "advice": "tavsiye", "lost": "kayıp", "follow": "takip et", "river": "nehir", "find": "bulmak", "people": "insanlar", "walked": "yürüdü", "days": "günler", "deep": "derin", "had": "sahipti", "cuts": "kesikler", "arms": "kollar", "insects": "böcekler", "laid": "bıraktı", "eggs": "yumurtalar", "wounds": "yaralar", "very": "çok", "painful": "acı verici", "saw": "gördü", "crocodiles": "timsahlar", "water": "su", "kept": "devam etti", "walking": "yürümek", "hungry": "aç", "tired": "yorgun", "Finally": "sonunda", "small": "küçük", "boat": "tekne", "waited": "bekledi", "Workers": "işçiler", "next": "ertesi", "day": "gün", "took": "götürdü", "hospital": "hastane" },
        questions: [ {q:"Was Maya 17 years old?", a_en:"Yes", a_tr:"Evet"}, {q:"Did lightning hit the plane?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the trees save her life?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she follow the river?", a_en:"Yes", a_tr:"Evet"}, {q:"Did insects lay eggs in her wounds?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she see crocodiles?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she walk for 11 days?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "15_TheSafariGuide.mp3": [{
        text: `David was a tour guide in Africa. He was driving his jeep alone to check a trail. The jeep got stuck in deep mud. He could not move it. Night came, and he heard lions roaring. He was far from the camp. He did not have a gun, only a knife. The lions smelled him and circled the jeep. They tried to bite the tires. David had to stay inside the open jeep. He did not sleep all night. He was thirsty and terrified. The next day, the sun was very hot. He waited for two days with the lions nearby. Finally, another guide saw his tire tracks and came to rescue him.`,
        dict: { "tour": "tur", "guide": "rehber", "driving": "süren", "alone": "yalnız", "check": "kontrol etmek", "trail": "yol/patika", "got stuck": "sıkıştı", "deep": "derin", "mud": "çamur", "could not": "yapamadı", "move": "hareket ettirmek", "Night": "gece", "came": "geldi", "heard": "duydu", "lions": "aslanlar", "roaring": "kükreyen", "far": "uzak", "camp": "kamp", "did not have": "sahip değildi", "gun": "silah", "only": "sadece", "knife": "bıçak", "smelled": "kokladı", "circled": "etrafını sardı", "tried": "denediler", "bite": "ısırmak", "tires": "lastikler", "had to": "zorundaydı", "stay": "kalmak", "inside": "içinde", "open": "açık", "sleep": "uyumak", "all": "tüm", "thirsty": "susamış", "terrified": "dehşete düşmüş", "next": "ertesi", "day": "gün", "sun": "güneş", "very": "çok", "hot": "sıcak", "waited": "bekledi", "two": "iki", "days": "günler", "nearby": "yakında", "Finally": "sonunda", "another": "başka bir", "saw": "gördü", "tire": "lastik", "tracks": "izler", "rescue": "kurtarmak" },
        questions: [ {q:"Was David a tour guide?", a_en:"Yes", a_tr:"Evet"}, {q:"Did his jeep get stuck in mud?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he hear lions?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he have a gun?", a_en:"No", a_tr:"Hayır"}, {q:"Did the lions bite the tires?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he stay inside the jeep?", a_en:"Yes", a_tr:"Evet"}, {q:"Did another guide rescue him?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "16_TheSandstormRunner.mp3": [{
        text: `Giovanni was a police officer who loved running. He joined a long race across the Sahara Desert. On the fourth day, a bad sandstorm started. The wind blew sand everywhere, and Giovanni could not see. He lost the trail. He kept running, but he went the wrong way. He ran out of water quickly. He was lost in the hot desert for nine days. He was so thirsty that he caught bats in an old building and drank their blood. He also drank his own urine. He wanted to die, but he kept walking. He lost 33 pounds. Finally, he found a camp of nomadic people. They gave him milk and saved him.`,
        dict: { "police": "polis", "officer": "memur", "loved": "sevdi", "running": "koşmak", "joined": "katıldı", "long": "uzun", "race": "yarış", "across": "boyunca", "Desert": "çöl", "fourth": "dördüncü", "day": "gün", "bad": "kötü", "sandstorm": "kum fırtınası", "started": "başladı", "wind": "rüzgar", "blew": "esti", "sand": "kum", "everywhere": "her yer", "could not": "yapamadı", "see": "görmek", "lost": "kaybetti/kayboldu", "trail": "patika/yol", "kept": "devam etti", "went": "gitti", "wrong": "yanlış", "way": "yol", "ran out": "tükendi", "water": "su", "quickly": "hızlıca", "hot": "sıcak", "nine": "dokuz", "days": "günler", "so": "çok", "thirsty": "susamış", "caught": "yakaladı", "bats": "yarasalar", "old": "eski", "building": "bina", "drank": "içti", "blood": "kan", "also": "ayrıca", "own": "kendi", "urine": "idrar", "wanted": "istedi", "die": "ölmek", "walking": "yürümek", "pounds": "pound (ağırlık)", "Finally": "sonunda", "found": "buldu", "camp": "kamp", "nomadic": "göçebe", "people": "insanlar", "gave": "verdiler", "milk": "süt", "saved": "kurtardılar" },
        questions: [ {q:"Was Giovanni a police officer?", a_en:"Yes", a_tr:"Evet"}, {q:"Did a sandstorm start?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he go the wrong way?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he catch bats?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he keep walking?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he lose 33 pounds?", a_en:"Yes", a_tr:"Evet"}, {q:"Did nomadic people save him?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "17_TheSnowTrap.mp3": [{
        text: `Sarah and John were driving home for Christmas. A heavy blizzard started. The snow fell very fast. Their car slid off the road and into a ditch. They could not get out. The snow covered the whole car. They were trapped inside. It was freezing. They knew they could not run the engine all the time because they would run out of gas or get poisoned. They ran the car for ten minutes every hour to get warm. They had no food, only some candy. They huddled together for three days. A snowplow driver saw the antenna of their car sticking out of the snow and dug them out.`,
        dict: { "driving": "araba süren", "home": "eve", "heavy": "ağır/şiddetli", "blizzard": "kar fırtınası", "started": "başladı", "snow": "kar", "fell": "düştü", "very": "çok", "fast": "hızlı", "car": "araba", "slid": "kaydı", "off": "dışına", "road": "yol", "into": "içine", "ditch": "hendek", "could not": "yapamadı", "get out": "çıkmak", "covered": "kapladı", "whole": "bütün", "trapped": "kapana kısılmış", "inside": "içinde", "freezing": "dondurucu", "knew": "biliyorlardı", "run": "çalıştırmak", "engine": "motor", "all": "tüm", "time": "zaman", "because": "çünkü", "run out": "tükenmek", "gas": "benzin", "get": "olmak", "poisoned": "zehirlenmiş", "ran": "çalıştırdı", "ten": "on", "minutes": "dakikalar", "every": "her", "hour": "saat", "warm": "sıcak", "had": "sahiptiler", "no": "yok/hiç", "food": "yiyecek", "only": "sadece", "some": "biraz", "candy": "şeker", "huddled": "toplandılar/sarıldılar", "together": "birlikte", "three": "üç", "days": "günler", "snowplow": "kar küreme", "driver": "sürücü", "saw": "gördü", "antenna": "anten", "sticking": "çıkıntı yapan", "dug": "kazdı", "out": "dışarı" },
        questions: [ {q:"Were they driving home for Christmas?", a_en:"Yes", a_tr:"Evet"}, {q:"Did a heavy blizzard start?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the car slide into a ditch?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the car covered in snow?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they have food?", a_en:"No", a_tr:"Hayır"}, {q:"Did they huddle together for three days?", a_en:"Yes", a_tr:"Evet"}, {q:"Did a snowplow driver find them?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "18_TheStoneGrip.mp3": [{
        text: `Leo loved adventure. He went hiking alone in a narrow canyon in Utah. While he was climbing down, a big rock moved. It fell and trapped his right arm against the canyon wall. Leo could not move. He had very little water and no food. He stood in the same spot for five days. He yelled for help, but nobody heard him. He drank his own urine because he was so thirsty. He knew he would die there. So, Leo made a brave and scary decision. He used a small, dull knife to cut off his own arm. He was free. He climbed down a cliff with one hand and walked six miles. A family on a hike found him.`,
        dict: { "loved": "sevdi", "adventure": "macera", "went": "gitti", "hiking": "doğa yürüyüşü", "alone": "yalnız", "narrow": "dar", "canyon": "kanyon", "While": "iken", "climbing": "tırmanırken", "down": "aşağı", "big": "büyük", "rock": "kaya", "moved": "hareket etti", "fell": "düştü", "trapped": "sıkıştırdı", "right": "sağ", "arm": "kol", "against": "karşı", "wall": "duvar", "could not": "yapamadı", "move": "hareket etmek", "had": "sahipti", "very": "çok", "little": "az", "water": "su", "no": "yok", "food": "yiyecek", "stood": "durdu", "same": "aynı", "spot": "nokta", "five": "beş", "days": "günler", "yelled": "bağırdı", "help": "yardım", "nobody": "hiç kimse", "heard": "duydu", "drank": "içti", "own": "kendi", "urine": "idrar", "because": "çünkü", "so": "çok", "thirsty": "susamış", "knew": "biliyordu", "die": "ölmek", "there": "orada", "made": "yaptı", "brave": "cesur", "scary": "korkutucu", "decision": "karar", "used": "kullandı", "small": "küçük", "dull": "kör", "knife": "bıçak", "cut off": "kesmek", "free": "özgür", "cliff": "uçurum", "one": "bir", "hand": "el", "walked": "yürüdü", "six": "altı", "miles": "miller", "family": "aile", "hike": "yürüyüş", "found": "buldu" },
        questions: [ {q:"Was Leo hiking in Utah?", a_en:"Yes", a_tr:"Evet"}, {q:"Did a rock trap his arm?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he yell for help?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he use a dull knife?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he cut off his own arm?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he walk six miles?", a_en:"Yes", a_tr:"Evet"}, {q:"Did a family find him?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "19_TheVoid.mp3": [{
        text: `Simon and Joe were climbing a high mountain in Peru. On the way down, Joe fell and broke his leg. Simon tried to lower Joe down with a rope. But Joe slipped over a cliff edge and hung in the air during a storm. Simon could not pull him up. To save himself, Simon cut the rope. Joe fell deep into a hole in the ice called a crevasse. Simon thought Joe was dead. But Joe was alive on a small ledge. He could not climb up, so he lowered himself deeper into the dark hole. He found a way out at the bottom. He crawled for three days with a broken leg and no food. He reached the camp just before Simon left.`,
        dict: { "climbing": "tırmanan", "high": "yüksek", "mountain": "dağ", "way": "yol", "down": "aşağı", "fell": "düştü", "broke": "kırdı", "leg": "bacak", "tried": "denedi", "lower": "indirmek", "rope": "ip", "slipped": "kaydı", "over": "üzerinden", "cliff": "uçurum", "edge": "kenar", "hung": "asıldı", "air": "hava", "during": "sırasında", "storm": "fırtına", "could not": "yapamadı", "pull": "çekmek", "up": "yukarı", "save": "kurtarmak", "himself": "kendisi", "cut": "kesti", "deep": "derin", "hole": "delik", "ice": "buz", "called": "adlandırılan", "crevasse": "buzul yarığı", "thought": "düşündü", "dead": "ölü", "alive": "canlı", "small": "küçük", "ledge": "çıkıntı", "climb": "tırmanmak", "so": "bu yüzden", "lowered": "indirdi", "deeper": "daha derin", "dark": "karanlık", "found": "buldu", "out": "dışarı", "bottom": "dip", "crawled": "emekledi", "three": "üç", "days": "günler", "broken": "kırık", "no": "yok", "food": "yiyecek", "reached": "ulaştı", "camp": "kamp", "just": "tam", "before": "önce", "left": "ayrıldı" },
        questions: [ {q:"Were Simon and Joe in Peru?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Joe break his leg?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Simon cut the rope?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Joe fall into a crevasse?", a_en:"Yes", a_tr:"Evet"}, {q:"Was Joe dead?", a_en:"No", a_tr:"Hayır"}, {q:"Did he find a way out?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he crawl for three days?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "20_TheWallOfFire.mp3": [{
        text: `Jack was camping in a national park. He smelled smoke. Suddenly, a huge forest fire appeared over the hill. The fire moved faster than a car. Jack tried to run to his car, but the fire blocked the road. He was surrounded by flames and thick smoke. He could not breathe well. He saw a river nearby. He jumped into the water and covered his head with a wet jacket. The fire burned the trees all around him. The heat was intense. He stayed in the water for five hours until the fire passed. A ranger found him the next morning.`,
        dict: { "camping": "kamp yapan", "national": "ulusal", "park": "park", "smelled": "kokladı", "smoke": "duman", "Suddenly": "aniden", "huge": "kocaman", "forest": "orman", "fire": "ateş/yangın", "appeared": "göründü", "over": "üzerinde", "hill": "tepe", "moved": "hareket etti", "faster": "daha hızlı", "than": "den (karşılaştırma)", "car": "araba", "tried": "denedi", "run": "koşmak", "blocked": "kapattı/engelledi", "road": "yol", "surrounded": "çevrelenmiş", "flames": "alevler", "thick": "kalın", "could not": "yapamadı", "breathe": "nefes almak", "well": "iyi", "saw": "gördü", "river": "nehir", "nearby": "yakında", "jumped": "atladı", "water": "su", "covered": "kapladı/örttü", "head": "kafa", "wet": "ıslak", "jacket": "ceket", "burned": "yaktı", "trees": "ağaçlar", "all": "tüm", "around": "etrafında", "heat": "ısı/sıcaklık", "intense": "yoğun", "stayed": "kaldı", "five": "beş", "hours": "saatler", "until": "kadar", "passed": "geçti", "ranger": "korucu", "found": "buldu", "next": "ertesi", "morning": "sabah" },
        questions: [ {q:"Was Jack camping in a national park?", a_en:"Yes", a_tr:"Evet"}, {q:"Did a huge fire appear?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the fire block the road?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he jump into a river?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he use a wet jacket?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he stay in the water for five hours?", a_en:"Yes", a_tr:"Evet"}, {q:"Did a ranger find him?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "21_TheWhiteSilence.mp3": [{
        text: `Marcus and Elias were on a university sports team. They flew over snowy mountains in a small plane to play a game. Suddenly, the wind pushed the plane down, and it crashed into the snow. Many of their friends died in the crash. The survivors had no warm clothes and very little food. It was extremely cold. They waited for help, but nobody came. After ten days, they heard on a radio that the police stopped looking for them. They were starving. Elias made a very hard choice to eat the bodies of their dead friends to stay alive. Later, a large amount of snow fell on their plane. Marcus and Elias knew they had to move. They walked for 12 days across the dangerous mountains without climbing equipment. Finally, they saw a farmer and asked for help. Helicopters came the next day.`,
        dict: { "university": "üniversite", "sports": "spor", "team": "takım", "flew": "uçtular", "over": "üzerinden", "snowy": "karlı", "mountains": "dağlar", "small": "küçük", "plane": "uçak", "play": "oynamak", "game": "oyun", "Suddenly": "aniden", "wind": "rüzgar", "pushed": "itti", "down": "aşağı", "crashed": "çarptı/düştü", "snow": "kar", "Many": "birçok", "friends": "arkadaşlar", "died": "öldü", "crash": "kaza", "survivors": "hayatta kalanlar", "had": "sahipti", "no": "yok", "warm": "sıcak", "clothes": "kıyafetler", "very": "çok", "little": "az", "food": "yiyecek", "extremely": "son derece", "cold": "soğuk", "waited": "beklediler", "help": "yardım", "nobody": "hiç kimse", "came": "geldi", "After": "sonra", "ten": "on", "days": "günler", "heard": "duydular", "radio": "radyo", "police": "polis", "stopped": "durdurdu", "looking for": "aramayı", "starving": "açlıktan ölen", "made": "yaptı", "hard": "zor", "choice": "seçim", "eat": "yemek", "bodies": "bedenler", "dead": "ölü", "stay": "kalmak", "alive": "canlı", "Later": "daha sonra", "large": "büyük", "amount": "miktar", "fell": "düştü", "knew": "biliyorlardı", "had to": "zorundaydılar", "move": "hareket etmek", "walked": "yürüdüler", "across": "karşısına", "dangerous": "tehlikeli", "without": "olmaksızın", "climbing": "tırmanma", "equipment": "ekipman", "Finally": "sonunda", "saw": "gördüler", "farmer": "çiftçi", "asked": "istediler", "Helicopters": "helikopterler", "next": "ertesi", "day": "gün" },
        questions: [ {q:"Did the plane crash into the snow?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the survivors have warm clothes?", a_en:"No", a_tr:"Hayır"}, {q:"Did they wait for ten days?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Elias eat dead bodies to stay alive?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they walk for 12 days?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they have climbing equipment?", a_en:"No", a_tr:"Hayır"}, {q:"Did they ask a farmer for help?", a_en:"Yes", a_tr:"Evet"} ]
    }]
};
